# Implementation of a simple neural network using PyTorch

This is an example of implementating a simple neural network using PyTorch, the network structure is as below:
![jupyter](./images/network.png)

In [135]:
import torch

In [136]:
# define training data set x and y
x = [[0.1,0.1, 0.1],
     [0.9, 0.9, 0.9],
     [0.2,0.1,0.1],
     [0.9,0.97,0.89],
     [0.1,0.2,0.1],
     [0.8,0.9,0.9],
     [0.3,0.1,0.4],
     [0.9,0.8,0.7],
     [0.11,0.22,0.15],
     [0.88,0.9,0.9]
   ]
y = [[0], [1], [0], [1], [0], [1], [0], [1], [0], [1]]

x = torch.tensor(x, dtype=torch.float)
y = torch.tensor(y, dtype=torch.float)

In [137]:
input_dim = 3
hidden_dim = 2
output_dim = 1
model = torch.nn.Sequential(
    torch.nn.Linear(input_dim, hidden_dim),
    torch.nn.Sigmoid(),
    torch.nn.Linear(hidden_dim, output_dim),
    torch.nn.Sigmoid()
)
print(model)

Sequential(
  (0): Linear(in_features=3, out_features=2, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=2, out_features=1, bias=True)
  (3): Sigmoid()
)


In [138]:
loss_fn = torch.nn.BCELoss()
learning_rate = 0.4
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
for t in range(500):
    y_pred = model(x)
    loss = loss_fn(y_pred, y)
    if t % 10 == 0:
        print(t, loss.item())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 0.8422020673751831
10 0.7034887075424194
20 0.6954593658447266
30 0.6902620196342468
40 0.684678316116333
50 0.6779319047927856
60 0.6693267226219177
70 0.6582313179969788
80 0.6441068649291992
90 0.6265054941177368
100 0.6050363779067993
110 0.5793431401252747
120 0.5491586923599243
130 0.514468789100647
140 0.47574228048324585
150 0.434093713760376
160 0.39121633768081665
170 0.34904301166534424
180 0.3092930316925049
190 0.2731453478336334
200 0.24115672707557678
210 0.2133740931749344
220 0.1895177662372589
230 0.16914871335029602
240 0.1517830789089203
250 0.1369573473930359
260 0.12425865232944489
270 0.11333353817462921
280 0.1038864254951477
290 0.09567325562238693
300 0.08849365264177322
310 0.0821836069226265
320 0.0766085833311081
330 0.07165806740522385
340 0.06724099814891815
350 0.06328190863132477
360 0.05971799045801163
370 0.05649681016802788
380 0.05357428267598152
390 0.05091313645243645
400 0.04848182201385498
410 0.046253401786088943
420 0.044204793870449066
430 

In [139]:
x1 = torch.tensor([0.9, 0.8, 0.92], dtype=torch.float)
print(model(x1))

tensor([0.9759], grad_fn=<SigmoidBackward>)


In [140]:
x2 = torch.tensor([0.11, 0.2, 0.18], dtype=torch.float)
print(model(x2))

tensor([0.0374], grad_fn=<SigmoidBackward>)


In [141]:
x3 = torch.tensor([0.9, 0.1, 0.92], dtype=torch.float)
print(model(x3))

tensor([0.8154], grad_fn=<SigmoidBackward>)
